<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Pricing.aspx.cs" Inherits="airesumebuilder.Pricing" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head runat="server">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AIRESUMSEBUILDER Pricing</title>
    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- Lucide Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lucide/0.263.1/lucide.min.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="min-h-screen bg-gradient-to-br from-gray-100 to-gray-200 p-4 md:p-8">
            <div class="max-w-7xl mx-auto">
                

                <!-- Pricing Section -->
                <div class="mb-8">
                    <div class="flex items-center justify-between mb-6">
                        <h1 class="text-3xl font-bold text-gray-800">Pricing</h1>
                        <div class="relative flex items-center bg-gray-200 rounded-full p-1">
                            <div id="toggleSlider" class="absolute left-1 w-20 h-8 bg-gray-800 rounded-full transition-transform duration-300 transform"></div>
                            <button type="button" id="annualBtn" class="relative z-10 px-4 py-2 text-sm font-medium rounded-full transition-colors duration-300 text-white">
                                Annual
                            </button>
                            <button type="button" id="monthlyBtn" class="relative z-10 px-4 py-2 text-sm font-medium rounded-full transition-colors duration-300 text-gray-600">
                                Monthly
                            </button>
                        </div>
                    </div>

                    <!-- Pricing Cards Grid -->
                    <div id="pricingGrid" class="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        <!-- Cards generated by script.js -->
                    </div>
                </div>
            </div>
        </div>
    </form>

    <!-- Lucide Icons Script -->
    <script>
        window.CheckIcon = `<svg class="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
        </svg>`;

        window.XIcon = `<svg class="w-3 h-3 text-gray-500" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>`;
    </script>

    <!-- Your pricing script -->
    <script src="script.js"></script>
    <script>
        // Pricing data with monthly and annual pricing
        const plans = [
            {
                name: "Recruit Basic",
                monthlyPrice: 499, // updated INR price
                annualPrice: 449, // discounted annual price
                originalPrice: null,
                monthlyYearlyBilled: 5988, // 499 * 12
                annualYearlyBilled: 5388, // 449 * 12
                description:
                    "Get started with essential tools to manage your team efficiently. Ideal for small teams with fundamental needs",
                isPopular: false,
                isActive: true,
                features: [
                    { name: "Access to core HR features", included: true },
                    { name: "Employee record management", included: true },
                    { name: "Basic reporting tools", included: true },
                    { name: "Manage up to 10 team members", included: true },
                    { name: "Track employee attendance", included: false },
                    { name: "Assign and monitor tasks", included: false },
                    { name: "Email support", included: false },
                    { name: "Simple onboarding process", included: false },
                    {
                        name: "Designed user-focused interfaces, optimized user",
                        included: false,
                    },
                ],
            },
            {
                name: "Talent Pro",
                monthlyPrice: 999,
                annualPrice: 849, // discount applied
                originalPrice: 999,
                monthlyYearlyBilled: 11988, // 999 * 12
                annualYearlyBilled: 10188, // 849 * 12
                description:
                    "A comprehensive solution for growing teams, offering enhanced features to streamline HR processes",
                isPopular: false,
                isActive: false,
                saveBadge: "Save 15%",
                features: [
                    { name: "Access to core HR features", included: true },
                    { name: "Employee record management", included: true },
                    { name: "Basic reporting tools", included: true },
                    { name: "Manage up to 10 team members", included: true },
                    { name: "Track employee attendance", included: true },
                    { name: "Assign and monitor tasks", included: true },
                    { name: "Email support", included: false },
                    { name: "Simple onboarding process", included: false },
                    {
                        name: "Designed user-focused interfaces, optimized user",
                        included: false,
                    },
                ],
            },
            {
                name: "HR Master",
                monthlyPrice: 1999,
                annualPrice: 1699, // discounted annual price
                originalPrice: null,
                monthlyYearlyBilled: 23988, // 1999 * 12
                annualYearlyBilled: 20388, // 1699 * 12
                description:
                    "Maximize team performance with premium tools and full customization options, perfect for larger organizations",
                isPopular: true,
                isActive: false,
                features: [
                    { name: "Access to core HR features", included: true },
                    { name: "Employee record management", included: true },
                    { name: "Basic reporting tools", included: true },
                    { name: "Manage up to 10 team members", included: true },
                    { name: "Track employee attendance", included: true },
                    { name: "Assign and monitor tasks", included: true },
                    { name: "Email support", included: true },
                    { name: "Simple onboarding process", included: true },
                    {
                        name: "Designed user-focused interfaces, optimized user",
                        included: true,
                    },
                ],
            },
        ];

        // State management
        let isAnnual = true;

        // Function to create a single pricing card
        function createPricingCard(plan, index) {
            const currencySymbol = "₹"; // Indian Rupee symbol
            const currentPrice = isAnnual ? plan.annualPrice : plan.monthlyPrice;
            const showOriginalPrice =
                isAnnual && plan.originalPrice && plan.name === "Talent Pro";
            const calculatedYearlyBilled = isAnnual
                ? plan.annualYearlyBilled
                : plan.monthlyYearlyBilled;

            const cardClasses = `relative rounded-3xl p-8 transition-all duration-300 hover:shadow-lg ${plan.isActive
                ? "bg-white shadow-lg border border-gray-200"
                : plan.name === "Talent Pro"
                    ? "bg-gray-800 text-white shadow-2xl transform scale-105 border-2 border-yellow-400"
                    : "bg-white shadow-lg border border-gray-200"
                }`;

            const titleColor =
                plan.name === "Talent Pro" ? "text-white" : "text-gray-800";
            const priceColor =
                plan.name === "Talent Pro" ? "text-yellow-400" : "text-gray-800";
            const periodColor =
                plan.name === "Talent Pro" ? "text-gray-300" : "text-gray-500";
            const descriptionColor =
                plan.name === "Talent Pro" ? "text-gray-300" : "text-gray-600";

            let badges = "";
            if (plan.isPopular) {
                badges += `
            <div class="absolute -top-3 right-6">
                <span class="bg-green-500 text-white px-3 py-1 rounded-full text-xs font-medium">
                    Popular
                </span>
            </div>
        `;
            }
            if (isAnnual && plan.saveBadge) {
                badges += `
            <div class="absolute -top-3 right-6">
                <span class="bg-yellow-400 text-gray-800 px-3 py-1 rounded-full text-xs font-bold">
                    ${plan.saveBadge}
                </span>
            </div>
        `;
            }
            if (plan.isActive) {
                badges += `
            <div class="absolute -top-3 left-6">
                <span class="bg-blue-500 text-white px-3 py-1 rounded-full text-xs font-medium">
                    Active
                </span>
            </div>
        `;
            }

            const originalPriceHtml = showOriginalPrice
                ? `<span class="text-lg text-gray-400 line-through mr-2 transition-all duration-300">${currencySymbol}${plan.originalPrice}</span>`
                : "";

            const featuresHtml = plan.features
                .map((feature) => {
                    const iconHtml = feature.included
                        ? `<div class="w-5 h-5 bg-green-500 rounded-full flex items-center justify-center">${window.CheckIcon}</div>`
                        : `<div class="w-5 h-5 bg-gray-300 rounded-full flex items-center justify-center">${window.XIcon}</div>`;

                    const textColor = feature.included
                        ? plan.name === "Talent Pro"
                            ? "text-white"
                            : "text-gray-700"
                        : plan.name === "Talent Pro"
                            ? "text-gray-400"
                            : "text-gray-400";

                    return `
            <div class="flex items-center space-x-3">
                <div class="flex-shrink-0">
                    ${iconHtml}
                </div>
                <span class="text-sm ${textColor}">
                    ${feature.name}
                </span>
            </div>
        `;
                })
                .join("");

            const buttonClasses = `w-full py-3 px-6 rounded-full font-medium transition-all duration-200 ${plan.isActive
                ? "bg-gray-200 text-gray-600 hover:bg-gray-300"
                : plan.name === "Talent Pro"
                    ? "bg-white text-gray-800 hover:bg-gray-100 font-semibold"
                    : "bg-gray-800 text-white hover:bg-gray-700"
                }`;

            return `
        <div class="${cardClasses}">
            ${badges}
            
            <!-- Plan Header -->
            <div class="mb-6">
                <h3 class="text-xl font-bold mb-4 ${titleColor}">
                    ${plan.name}
                </h3>
                
                <div class="flex items-baseline mb-2">
                    ${originalPriceHtml}
                    <span class="text-4xl font-bold transition-all duration-300 ${priceColor}">
                        ${currencySymbol}${currentPrice}
                    </span>
                    <span class="ml-1 text-sm ${periodColor}">
                        / month
                    </span>
                </div>
                
                <p class="text-xs mb-4 transition-all duration-300 ${periodColor}">
                    ${currencySymbol}${calculatedYearlyBilled} billed ${isAnnual ? "yearly" : "yearly"
                }
                </p>
                
                <p class="text-sm leading-relaxed ${descriptionColor}">
                    ${plan.description}
                </p>
            </div>

            <!-- Features List -->
            <div class="space-y-3 mb-8">
                ${featuresHtml}
            </div>

            <!-- CTA Button -->
            <button class="${buttonClasses}">
                ${plan.isActive ? "Cancel" : "Start 7-days Free Trial"}
            </button>
        </div>
    `;
        }

        // Function to render all pricing cards
        function renderPricingCards() {
            const pricingGrid = document.getElementById("pricingGrid");
            const cardsHtml = plans
                .map((plan, index) => createPricingCard(plan, index))
                .join("");
            pricingGrid.innerHTML = cardsHtml;
        }

        // Function to handle button toggle states with smooth animation
        function setupToggleButtons() {
            const annualBtn = document.getElementById("annualBtn");
            const monthlyBtn = document.getElementById("monthlyBtn");
            const toggleSlider = document.getElementById("toggleSlider");

            annualBtn.addEventListener("click", function () {
                if (!isAnnual) {
                    isAnnual = true;
                    toggleSlider.style.transform = "translateX(0)";
                    annualBtn.classList.add("text-white");
                    annualBtn.classList.remove("text-gray-600");
                    monthlyBtn.classList.add("text-gray-600");
                    monthlyBtn.classList.remove("text-white");
                    renderPricingCards();
                }
            });

            monthlyBtn.addEventListener("click", function () {
                if (isAnnual) {
                    isAnnual = false;
                    toggleSlider.style.transform = "translateX(calc(100% - 0.25rem))";
                    monthlyBtn.classList.add("text-white");
                    monthlyBtn.classList.remove("text-gray-600");
                    annualBtn.classList.add("text-gray-600");
                    annualBtn.classList.remove("text-white");
                    renderPricingCards();
                }
            });
        }

        // Initialize the page when DOM is loaded
        document.addEventListener("DOMContentLoaded", function () {
            renderPricingCards();
            setupToggleButtons();
        });

    </script>
</body>
</html>
